Traceback (most recent call last):
  File "/Users/bytedance/Desktop/codes/xenon_generation_sft/venv/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/bytedance/Desktop/codes/xenon_generation_sft/venv/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/bytedance/Desktop/codes/xenon_generation_sft/venv/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/bytedance/.pyenv/versions/3.9.18/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/bytedance/Desktop/codes/xenon_generation_sft/venv/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/bytedance/Desktop/codes/xenon_generation_sft/venv/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/bytedance/Desktop/codes/xenon_generation_sft/venv/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
water_system_columns = water_system_api.get_table_column_name(print_to_console=False)
sdwis_drink_water.utils_for_jupyter_print.print_columns(water_system_columns)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m water_system_columns [38;5;241m=[39m water_system_api[38;5;241m.[39mget_table_column_name(print_to_console[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[0;32m----> 2[0m [43msdwis_drink_water[49m[38;5;241m.[39mutils_for_jupyter_print[38;5;241m.[39mprint_columns(water_system_columns)

[0;31mNameError[0m: name 'sdwis_drink_water' is not defined

